// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_BASICATTACK);  //micro  (extern verison)-> says this is a declaration only, which explains something exist
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_COMBO_CHANGE);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_COMBO_CHANGE_Combo01);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_COMBO_CHANGE_Combo02);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_COMBO_CHANGE_Combo03);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_COMBO_CHANGE_Combo04);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_COMBO_CHANGE_End);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_COMBO_DAMAGE);



